### ISSUE TITLE
能否自定义上方日期颜色？

### ISSUE THREAD

**Issue by Dorbmon** [rhymelph/r_calendar#4]
顶端的日期能否自定义颜色？或者使用自定义Widget？

**Comment by rhymelph** [comment]
不太明白你的问题，能否详细的描述一下？

**Comment by rhymelph** [comment]
关闭了，如果还有其它问题，欢迎随时打开

**Comment by Dorbmon** [comment]
> 关闭了，如果还有其它问题，欢迎随时打开

指的就是上方的日期指示。例如2020-03-31 ，这个默认是红色的，能否换成自定义的Widget

**Comment by Dorbmon** [comment]
例如 
![example](https://github.com/rhymelph/r_calendar/blob/master/screen/s1.png) 上方的红色日期指示

**Comment by rhymelph** [comment]
可以重写`RCalendarCustomWidget`里面的`Widget buildTopWidget(BuildContext context, RCalendarController controller)`方法实现，详情可见https://github.com/rhymelph/r_calendar/blob/master/r_calendar/lib/src/r_calendar_custom_widget.dart

**Comment by Dorbmon** [comment]
谢谢
