### ISSUE TITLE
想要清空selectedDates的数据

### ISSUE THREAD

**Issue by gneL1** [rhymelph/r_calendar#5]
作者你好。我在0.1.5版本中是通过下面的方式来清空被选中的日期
    _controller.selectedDates.clear();
    _controller.notifyListeners();

但是在^0.1.6版本中这样操作没效果。
在源码里
![图片](https://user-images.githubusercontent.com/38184470/78089444-03250f00-73fa-11ea-8035-8b97c2a8df83.png)
get和set同名的话改变不了selectedDates的值吧。。

**Comment by rhymelph** [comment]
可以试试`_controller.selectedDates.clear();`改为`_controller.selectedDates = [];`
