### ISSUE TITLE
能否将点击事件暴露出来呢

### ISSUE THREAD

**Issue by Horace7** [rhymelph/r_calendar#6]
就是单选和多选的点击事件，现在在
```dart
..addListener(() {
      print(controller.selectedDate);
    });
```
中监听时，每次翻页也会监听到变化，虽然值没有变化。
这就导致了我将它作为一个组件时，还需要暂存一个值来判断每次翻页或点击时是否改变，用来进行关闭弹窗的操作。

**Comment by jeromekai** [comment]
切换月  和 点击日期用的是一个回调，希望能有多个回调区分

**Comment by rhymelph** [comment]
已经有个点击拦截了，可以将值传递出来，自行实现
